[project]
name = "floxdemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ddtrace>=3.0.0",
    "mysqlclient>=2.2.7",
]
